version: '2'
services:
  redis:
    container_name: "redis-for-gingo"
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_MAX_MEMORY: 2048mb

  gingo:
    container_name: "gingo-dev"
    image: clsung/gingo:latest
    ports:
      - "8080:8080"
    links:
      - redis
    command: sh -c "/gingo -redis-address=redis:6379"


